### ISSUE TITLE
MacOS 13 apple build fail/high processor usage

### ISSUE THREAD

**Issue by naymapl** [jpochyla/psst#356]
hello again.
I try to build fresh psst app - developer app build ok but have large size psst-gui have almost 68MB and use a lot od processor around 30%.

![Zrzut ekranu 2022-11-1 o 09 23 21](https://user-images.githubusercontent.com/24625283/199190782-ccd87a10-2b90-4497-905d-959b4e8595b6.jpg)

When I try to build Release build:

```
cd psst-gui
cargo build --release
```

i got error:

```
Compiling lock_api v0.4.9
   Compiling num-bigint v0.4.3
error: failed to run custom build command for `quote v1.0.21`

Caused by:
  process didn't exit successfully: `/Users/naymapl/psst/target/release/build/quote-7267b0cc1d4bd6e3/build-script-build` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...

```

This hight 30% usage od cpu is coming when you start any track. When app is just iopen without plaing anything cpu ussage is around 1.5-1.8%.
Any idea ?

**Comment by cloudybyte** [comment]
It looks live you cancelled the build by sending a SIGKILL signal to the process.
Try running `cargo build --release` again, and leave it sit there for some time. Release builds can take quite some time.

The unusually high CPU usage is most likely due to you running a debug build (which sacrifices optimizations in favor of faster build times). I'd suggest trying to [download a prebuilt binary](https://github.com/jpochyla/psst#pre-built-binaries).
