### ISSUE TITLE
No playlist on psst-gui and failed to read json error

### ISSUE THREAD

**Issue by slovanos** [jpochyla/psst#461]
**Bug description:** There is no playlist  menu.
 
- Error shown on the gui: 
  "failed to read JSON"

- Error shown on the terminal:
ERROR psst_gui::webapi::client] failed to read local tracks: No such file or directory (os error 2)

**To Reproduce**
Simple open the app with ./psst-gui 

**Environment**
 OS: Linux Mint 21

![psst-error](https://github.com/jpochyla/psst/assets/48527469/8711ac10-632d-4daf-9f87-65d14ef8649c)

**Comment by mackcoding** [comment]
I am having the same issue. I get an error saying network timed out, and it gives an api url. I can't see anything that would be pulled with the API.

This started out of nowhere. I'm able to access the API directly with no issue, so I don't believe it's a network issue. This started yesterday just like slovanos is saying.

**Comment by peorth80** [comment]
Same issue here! Probably the JSON changed 
![image](https://github.com/jpochyla/psst/assets/16003799/65f1dc37-991d-4871-8698-3e2988e89c02)

**Comment by mackcoding** [comment]
I'm not even getting that far:
![image](https://github.com/jpochyla/psst/assets/10917563/9c38e0d1-c972-45cf-a55d-9497b668de13)

**Comment by nicolasf** [comment]
Same issue here on MacOS.

The odd thing is that the file it's trying to load with local : load_tracks_for_user has some content that is unrelated to Spotify or PSST. I have no idea why.

It starts with "SPCOLocalFilesStoraged` " and continues with data unrelated to Spotify.

**Comment by dylannorthrup** [comment]
I attempted to add some debugging in the "make request" code path, but I am not a rust programmer so it is possible/likely I did something incorrectly.

After adding `log::info!(...)` bits and various values of `export PSST_LOG=debug,function=trace`, I could see requests initiated from [`get_playlists`](https://github.com/jpochyla/psst/blob/0cb4f6964b5ba771182ccfe005260a86a494ef92/psst-gui/src/webapi/client.rs#L503) and dispatched to [`for_all_pages`](https://github.com/jpochyla/psst/blob/0cb4f6964b5ba771182ccfe005260a86a494ef92/psst-gui/src/webapi/client.rs#L159) which calls [`self.load`](https://github.com/jpochyla/psst/blob/0cb4f6964b5ba771182ccfe005260a86a494ef92/psst-gui/src/webapi/client.rs#L125-L129) that calls [`ureq::Response.into_json`](https://docs.rs/ureq/latest/ureq/struct.Response.html#method.into_json). Because `into_json` [consumes the contents of the response](https://docs.rs/ureq/latest/ureq/struct.Response.html#), it's non-obvious how to log the contents of the request *and* have that request used by the `psst-gui` client.

Unlike @mackcoding, it seems I'm able to get a response, but there's something about the returned JSON that `psst-gui` does not like. Happy to re-run if someone can provide a way to simultaneously log the response (or print to STDOUT) and have it used by `psst`, but since is `rust` is outside my area of knowledge, I'll need someone else to provide the code for it (or point to an example of it elsewhere).

![image](https://github.com/jpochyla/psst/assets/1229014/bbbd6213-3d69-4a5f-bc4e-ac466c423471)

**Comment by kingosticks** [comment]
Recently (few weeks back) Spotify changed the format of some of their responses so that empty lists return 'null' instead of being actual empty lists like they are supposed to be. I had to change my (python) app to handle that, maybe you're hitting the same thing here.

The other problem in this thread appears to be the different case of where they turned off one of their undocumented (private) endpoints. I did see someone with a workaround for that but I helpfully can't find it now. I don't use the undocumented endpoints myself (in a futile attempt to avoid Spotify breaking my app all the time with their stupid random changes).

**Comment by nicolasf** [comment]
> Recently (few weeks back) Spotify changed the format of some of their responses so that empty lists return 'null' instead of being actual empty lists like they are supposed to be. I had to change my (python) app to handle that, maybe you're hitting the same thing here.

Took a stab at fixing the error based on this info from @kingosticks (thanks!).
Here's a PR: https://github.com/jpochyla/psst/pull/464

Tested locally and it looks good to me, but I'm not familiar with Rust, so please review it :).

**Comment by kingosticks** [comment]
> Recently (few weeks back) Spotify changed the format of some of their responses so that empty lists return 'null' instead of being actual empty lists like they are supposed to be. I had to change my (python) app to handle that, maybe you're hitting the same thing here.
> 
> The other problem in this thread appears to be the different case of where they turned off one of their undocumented (private) endpoints. I did see someone with a workaround for that but I helpfully can't find it now. I don't use the undocumented endpoints myself (in a futile attempt to avoid Spotify breaking my app all the time with their stupid random changes).

Regarding the other problem, with endpoints being removed (made-for-x etc), I found the related issue I was looking for: https://github.com/michaelherger/Spotty-Plugin/issues/117

I'm not sure if the fix they used there is directly relevant here, I don't personally use either software. But maybe it helps.
