### ISSUE TITLE
make provided binaries more prominent

### ISSUE THREAD

**Issue by Uzay-G** [jpochyla/psst#89]
Binaries from the github actions CI are a bit hidden in the installation process, and I had to go look at the workflow file, after seeing them mentioned in the issues, and then look up where to find github artifacts for a given workflow.

Maybe it would be more convenient to mention these in the readme?

**Comment by a-nldisr** [comment]
Another question regarding this:
In the first alinea there is talk about Mac, but the documentation only lists how to install on Debian.

**Comment by jtbayly** [comment]
Yes, I have a mac, and I cannot figure out how to install this app.

**Comment by grischard** [comment]
In [JOSM](https://github.com/JOSM/josm/blob/master/.github/workflows/ant.yml) we've just created a pre-release for every build instead of an artifact. We also sign and notarize the macOS packages.

If you've landed here looking for a psst download, here are recent builds:

* [psst-deb](https://github.com/jpochyla/psst/suites/3441075135/artifacts/81589459)
* [psst-gui-Linux](https://github.com/jpochyla/psst/suites/3441075135/artifacts/81589460)
* [psst-gui-Windows](https://github.com/jpochyla/psst/suites/3441075135/artifacts/81589462)
* [psst-gui-macOS](https://github.com/jpochyla/psst/suites/3441075135/artifacts/81589461) (unzip, then right-click -> Open)

**Comment by jtbayly** [comment]
Thanks! 

I downloaded the psst-gui-MacOS, but once I unzip it, it doesn't look like an app. (It's "kind" is "document" in the Finder.) When I try to run it, it opens in Textedit. Not sure what's wrong. (I'm on an M1 MacBook Air, in case it matters.)

**Comment by mendelk** [comment]
@jtbayly I had the same issue, and this is how I got it to work:

- Unzipped it
- Open a terminal
- `cd ~/Downloads/`
- `chmod 755 psst-gui`
- `xattr -d com.apple.quarantine psst-gui`
- `./psst-gui`

**Comment by jpochyla** [comment]
This will be also improved by #82, soon.
